version : '3.3'
services:
    roachdb:
        image: cockroachdb/cockroach:latest
        networks:
            axolotl:
                aliases:
                    - roachdb
        volumes:
            - type: volume
              source: roach-volumes
              target: /cockroach/cockroach-data
              volume:
                nocopy: true
        ports:
            - target: 26257
              published: 26257
              protocol: tcp
            - target: 8080
              published: 8080
              protocol: tcp
        command: start --insecure

    mariadb:
        image: mariadb:latest
        networks:
            axolotl:
                aliases:
                    - mariadb
        volumes:
            - type: volume
              source: mariadb-volumes
              target: /var/lib/mysql
              volume:
                nocopy: true
        environment:
            MYSQL_ROOT_PASSWORD: 50master
        ports:
            - target: 3306
              published: 3306
              protocol: tcp

    phpmyamdin:
        image: phpmyadmin/phpmyadmin:latest
        networks:
            axolotl:
                aliases:
                    - phpmyadmin
        environment:
            PMA_HOST: mariadb 
        ports:
            - target: 80
              published: 8081
              protocol: tcp

    mongo:
        image: mongo:4.0
        networks:
            axolotl:
                aliases:
                    - mongo
        ports:
            - target: 27017
              published: 27017
              protocol: tcp
        volumes:
            - type: volume
              source: mongo-volumes
              target: /data/db
              volume:
                nocopy: true
            - type: volume
              source: mongo-volumes
              target: /data/configdb
              volume:
                nocopy: true

    mongo-admin:
        image: mrvautin/adminmongo:latest
        networks:
            axolotl:
              aliases:
                - mongoadmin
        ports:
            - target: 80
              published: 8082
              protocol: tcp
        environment:
            PORT: 80
            LOCALE: "zh-tw"
            CONTEXT: "http://mongo:27017"

    redis:
        image: redis:5.0-rc-alpine
        networks:
            axolotl:
                aliases:
                    - redis
        ports:
            - target: 6379
              published: 6379
              protocol: tcp
        volumes:
            - type: bind
              source: $PWD/config/redis.conf
              target: /usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf

    redis-cmd:
        image: tenstartups/redis-commander:latest
        networks:
            axolotl:
              aliases:
                - redisadmin
        ports:
            - "8083:8081"
        depends_on:
            - redis

        command: --redis-host redis

    glances:
        image: nicolargo/glances
        networks:
            axolotl:
        ports:
          - "61208-61209:61208-61209"
        environment:
          GLANCES_OPT: "-w"
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        pid: "host"

    portainer:
        image: portainer/portainer:latest
        networks:
            axolotl:
              aliases:
                - portainer
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
            - type: volume
              source: portainer-volumes
              target: /data
              volume:
                nocopy: true
        ports:
            - target: 9000
              published: 9000
              protocol: tcp

volumes:
    mongo-volumes:
    mariadb-volumes:
    roach-volumes:
    portainer-volumes:

networks:
    axolotl:
        external:
            name: axolotl
